### ISSUE TITLE
SET_TARGET_PROPERTIES for UnmanagedClass

### ISSUE THREAD

**Issue by johanrelefors** [Aschratt/DotNetWithCMake#5]
I cloned your repository and got this error from CMake

Error		CMake Error at src/UnmanagedLib/CMakeLists.txt:8 (SET_TARGET_PROPERTIES):
  SET_TARGET_PROPERTIES called with illegal arguments, maybe missing a
  PROPERTIES specifier?	UnmanagedLib	C:\**\Source\Repos\DotNetWithCMake\src/UnmanagedLib/CMakeLists.txt	8	

Changing the referred line to 
SET_TARGET_PROPERTIES(${PROJECT_NAME} PROPERTIES PUBLIC_HEADER "include/UnmanagedClass.h")
fixed this.

**Comment by crud89** [comment]
Thank you, I've somehow missed to add the keyword.

Fixed with a4ebc83589a8ce5a31a24769b2cc91c635c6023a.

**Comment by johanrelefors** [comment]
No problem. Thank you for making the repository available!

Johan

Den sön 28 mars 2021 18:55Carsten Rudolph ***@***.***> skrev:
