### ISSUE TITLE
Request: Update template to show how to specify langversion 8

### ISSUE THREAD

**Issue by GerritNG** [Aschratt/DotNetWithCMake#8]
The root CMakeLists file sets langversion in a flags variable, which is then overwritten, so it doesn't do anything.

https://github.com/crud89/DotNetWithCMake/blob/b2645ea3fcef56f9b7e0f6f0b362a0ecd04f783a/CMakeLists.txt#L10-L21

I tried fixing this, as I have a C# project which requires `#nullable enable`, and therefore requires C# version 8... but setting `/langversion:8` as the flags doesn't appear to actually work (CMake 3.20), so I'm starting to think that this isn't how this is supposed to be set up. Feels like I'm missing something obvious.

**Comment by GerritNG** [comment]
Apparently my cmake version predates https://gitlab.kitware.com/cmake/cmake/-/merge_requests/6031, so setting `langversion:8` just doesn't work... okay, hopefully newer VS 2019 has newer cmake...

**Comment by crud89** [comment]
Thanks for the hint. You are of course right regarding the language version, I will fix the issue as soon as I find time for it. If you are only using C# you can drop the lines below setting the language version and support AnyCPU. Also keep in mind that newer language versions may require SDK style projects, which should work, but I haven't tried this yet. If you have some feedback on this, feel free to share. 🙂

I also recommend switching to Visual Studio 2022. CMake is regularly updated there and you can specify a custom installation if you need a later version.

**Comment by crud89** [comment]
@GerritNG I've updated the project and it now works with C# 12 for me under Visual Studio 2022 (17.9.0). If you have any problems getting it to run, just let me know. Thanks for reporting this! 🙂
